//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class home:public drogon::DrTemplate<home>
{
public:
	home(){};
	virtual ~home(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
